// Licensed under the Apache License, Version 2.0 or the MIT License.
// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright Tock Contributors 2026.
// Copyright Better Bytes 2026.

//! Demonstrates how a mostly-safe DMA abstraction can be built on top of generated register code.

// -------------------------------------------------------------------------------------------------
// DMA interface crate.
// -------------------------------------------------------------------------------------------------

// This is obviously simplified relative to a real DMA crate, e.g. it only supports 'static
// buffers.
mod safe_dma {
    use core::ptr::NonNull;

    /// State type: indicates this DMA operation is idle.
    pub struct Idle;

    /// State type: indicates this DMA operation is in use.
    pub struct Running(pub NonNull<[u8]>);

    /// Dynamic state type: this tracks whether the DMA operation is idle or running at runtime
    /// rather than compile type.
    #[derive(Clone, Copy)]
    pub struct Dynamic(pub Option<NonNull<[u8]>>);

    impl From<Idle> for Dynamic {
        fn from(_: Idle) -> Dynamic {
            Dynamic(None)
        }
    }
    impl From<Running> for Dynamic {
        fn from(Running(ptr): Running) -> Dynamic {
            Dynamic(Some(ptr))
        }
    }
    impl TryFrom<Dynamic> for Idle {
        type Error = ();
        fn try_from(Dynamic(option): Dynamic) -> Result<Idle, ()> {
            match option {
                None => Ok(Idle),
                Some(_) => Err(()),
            }
        }
    }
    impl TryFrom<Dynamic> for Running {
        type Error = ();
        fn try_from(Dynamic(option): Dynamic) -> Result<Running, ()> {
            option.map(Running).ok_or(())
        }
    }
}

// -------------------------------------------------------------------------------------------------
// Driver using the safe DMA interface.
// -------------------------------------------------------------------------------------------------

use core::{cell::UnsafeCell, ptr::NonNull};
use safe_dma::{Dynamic, Idle, Running};
use tock_registers::{mmio64_register_layouts, Mmio64, UnsafeRead, UnsafeWrite};

mmio64_register_layouts! {
    /// Register for a DMA-based UART.
    uart {
        /// Pointer to the receive buffer.
        // Note: rx_buffer and tx_buffer really should be pointers, but UIntLike is not yet
        // implemented for pointers, so using `usize` for now.
        0 => rx_buffer: usize { UnsafeRead, UnsafeWrite },
        /// Length of the buffer to receive
        8 => rx_len: usize { UnsafeRead, UnsafeWrite },
        /// Set to 1 to receive, 0 to stop.
        16 => rx_enable: u8 { UnsafeRead, UnsafeWrite },
        17 => _,
        /// Pointer to the transmit buffer.
        24 => tx_buffer: usize { UnsafeRead, UnsafeWrite },
        /// Length of the buffer to transmit
        32 => tx_len: usize { UnsafeRead, UnsafeWrite },
        /// Set to 1 to transmit, 0 to stop.
        40 => tx_enable: u8 { UnsafeRead, UnsafeWrite },
    }
}

// This struct and its impls would be generated by a procedural macro (I tried to prototype this
// using macro_rules!, but macro_rules! isn't powerful enough to generate some of the generics on
// its own). The macro invocation would look something like:
//
// dma! {
//     // Specifies the name of the struct and the peripheral module it corresponds to.
//     UartDma(uart) {
//         // Each of these blocks corresponds to a DMA buffer supported by the peripheral. Each
//         // specifies:
//         //     1. The name of the field in the struct (rx)
//         //     2. The name of the state generic (RX)
//         //     3. address: The name of the address register, which must be an UnsafeWrite usize.
//         //     4. len: The name of the len register, which must be an UnsafeWrite usize.
//         //     5. enable: The code to start the DMA operation.
//         //     6. disable: The code to stop the DMA operation.
//         rx: RX read_write {
//             address: rx_buffer,
//             len: rx_len,
//             enable: unsafe { self.registers.rx_enable().set(1) },
//             disable: unsafe { self.registers.rx_enable().set(0) },
//         }
//         tx: TX read_only {
//             address: tx_buffer,
//             len: tx_len,
//             enable: unsafe { self.registers.tx_enable().set(1) },
//             disable: unsafe { self.registers.tx_enable().set(0) },
//         }
//     }
// }

struct UartDma<R: uart::Interface, RX, TX> {
    registers: R,
    rx: RX,
    tx: TX,
}

impl<R: uart::Interface> UartDma<R, Idle, Idle> {
    /// Safety: Can only construct this once for each peripheral instance.
    pub const unsafe fn new(registers: R) -> Self {
        Self {
            registers,
            rx: Idle,
            tx: Idle,
        }
    }
}

impl<R: uart::Interface, RX1, TX1> UartDma<R, RX1, TX1> {
    /// Performs conversions like:
    ///
    /// 1. UartDma<R, Idle, Running> -> UartDma<R, Dynamic, Running>
    /// 2. UartDma<R, Idle, Running> -> UartDma<R, Idle, Dynamic>
    /// 3. UartDma<R, Idle, Running> -> UartDma<R, Dynamic, Dynamic>
    ///
    /// Basically, into_dynamic moves the type-level information into runtime information.
    pub fn into_dynamic<RX2: From<RX1>, TX2: From<TX1>>(self) -> UartDma<R, RX2, TX2> {
        UartDma {
            registers: self.registers,
            rx: From::from(self.rx),
            tx: From::from(self.tx),
        }
    }

    /// Performs conversions like:
    ///
    /// 1. UartDma<R, Dynamic, Dynamic> -> UartDma<R, Dynamic, Running>
    /// 2. UartDma<R, Dynamic, Dynamic> -> UartDma<R, Idle, Dynamic>
    /// 3. UartDma<R, Dynamic, Dynamic> -> UartDma<R, Idle, Running>
    ///
    /// Basically, this checks if a UartDma with more runtime information matches a type with more
    /// type-level information.
    pub fn into_static<RX2: TryFrom<RX1>, TX2: TryFrom<TX1>>(
        self,
    ) -> Result<UartDma<R, RX2, TX2>, Self>
    where
        RX1: Copy,
        TX1: Copy,
    {
        match (TryFrom::try_from(self.rx), TryFrom::try_from(self.tx)) {
            (Ok(rx), Ok(tx)) => Ok(UartDma {
                registers: self.registers,
                rx,
                tx,
            }),
            _ => Err(self),
        }
    }
}

impl<R: uart::Interface, TX> UartDma<R, Idle, TX> {
    pub fn start_rx(self, buffer: &'static mut [u8]) -> UartDma<R, Running, TX> {
        let buffer = NonNull::from(buffer);

        // Do the DMA fence operation here.

        #[rustfmt::skip]
        unsafe { self.registers.rx_buffer().set(buffer.cast::<u8>().as_ptr() as usize) };
        //                      ^^^^^^^^^ Pasted from macro input.
        unsafe { self.registers.rx_len().set(buffer.len()) };
        //                      ^^^^^^ Pasted from macro input.
        unsafe { self.registers.rx_enable().set(1) };
        //       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Pasted from macro input.
        UartDma {
            registers: self.registers,
            rx: Running(buffer),
            tx: self.tx,
        }
    }
}

impl<R: uart::Interface, RX> UartDma<R, RX, Idle> {
    pub fn start_tx(self, buffer: &'static mut [u8]) -> UartDma<R, RX, Running> {
        let buffer = NonNull::from(buffer);

        // Do the DMA fence operation here.

        #[rustfmt::skip]
        unsafe { self.registers.tx_buffer().set(buffer.cast::<u8>().as_ptr() as usize) };
        //                      ^^^^^^^^^ Pasted from macro input.
        unsafe { self.registers.tx_len().set(buffer.len()) };
        //                      ^^^^^^ Pasted from macro input.
        unsafe { self.registers.tx_enable().set(1) };
        //       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Pasted from macro input.
        UartDma {
            registers: self.registers,
            rx: self.rx,
            tx: Running(buffer),
        }
    }
}

impl<R: uart::Interface, TX> UartDma<R, Running, TX> {
    pub fn stop_rx(self) -> (UartDma<R, Idle, TX>, &'static mut [u8]) {
        unsafe { self.registers.rx_enable().set(0) };
        //       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Pasted from macro input.

        // Do the DMA fence operation here.

        (
            UartDma {
                registers: self.registers,
                rx: Idle,
                tx: self.tx,
            },
            // Safety: We know the DMA was stopped, and this is the exact opposite conversion from
            // start_rx (so this pointer went reference -> NonNull -> reference). The lifetime on
            // the original reference was 'static so 'static is fine here too.
            unsafe { &mut *self.rx.0.as_ptr() },
        )
    }
}

impl<R: uart::Interface, RX> UartDma<R, RX, Running> {
    pub fn stop_tx(self) -> (UartDma<R, RX, Idle>, &'static mut [u8]) {
        unsafe { self.registers.tx_enable().set(0) };
        //       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Pasted from macro input.

        // Do the DMA fence operation here.

        (
            UartDma {
                registers: self.registers,
                rx: self.rx,
                tx: Idle,
            },
            // Safety: We know the DMA was stopped, and this is the exact opposite conversion from
            // start_rx (so this pointer went reference -> NonNull -> reference). The lifetime on
            // the original reference was 'static so 'static is fine here too.
            unsafe { &mut *self.tx.0.as_ptr() },
        )
    }
}

// -------------------------------------------------------------------------------------------------
// End of generated code
// -------------------------------------------------------------------------------------------------

#[cfg(target_pointer_width = "64")]
fn main() {
    // Setup: create a fake peripheral (we don't need behavior, so using Real with a local buffer
    // is fine), construct the UartDma, and allocate 'static buffers.
    let peripheral = UnsafeCell::new([0usize; 6]);
    let mmio = Mmio64::new(NonNull::new(peripheral.get()).unwrap().cast());
    // Safety: Our fake peripheral is a good-enough model of the theoretical UART.
    let registers = unsafe { uart::Real::new(mmio) };
    // Safety: only calling this once.
    let uart_dma = unsafe { UartDma::new(registers) };
    // Allocate 'static buffers.
    let buffer1 = Box::leak(Box::new([1, 2, 3, 4]));
    let buffer2 = Box::leak(Box::new([5, 6, 7, 8]));

    // Demonstrate running receive and transmit operations using DMA.
    let uart_dma = uart_dma.start_rx(buffer1);
    let uart_dma = uart_dma.start_tx(buffer2);
    // Demonstrate that we can move the typestate into runtime states. This is how driver structs
    // would likely store the UartDma.
    let uart_dma: UartDma<uart::Real, Dynamic, Dynamic> = uart_dma.into_dynamic();
    // Convert the runtime states back into typestates, stop the operations, and clean up the
    // buffers.
    let uart_dma = uart_dma
        .into_static()
        .unwrap_or_else(|_| panic!("wrong state"));
    let (uart_dma, buffer1) = uart_dma.stop_rx();
    let (_, buffer2) = uart_dma.stop_tx();

    // Deallocate the buffers.
    let _ = unsafe { Box::from_raw(buffer1) };
    let _ = unsafe { Box::from_raw(buffer2) };
}

#[cfg(not(target_pointer_width = "64"))]
fn main() {}
