// Licensed under the Apache License, Version 2.0 or the MIT License.
// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright Tock Contributors 2026.
// Copyright Better Bytes 2026.

//! Demonstrates how a typestate interface similar to abacus-registers could be integrated with
//! register_map!.

// -------------------------------------------------------------------------------------------------
// typestate crate
// -------------------------------------------------------------------------------------------------

mod typestate {
    use tock_registers::{DataType, Register};

    pub trait TypestateWrite: Register {
        /// Token type that can only be constructed by the generated wrapper module.
        type Token;

        /// Same as tock_registers::Write::set, but with the token passed to seal this to the
        /// generated wrapper module.
        fn set(self, token: Self::Token, value: <Self::DataType as DataType>::Value);
    }

    #[macro_export]
    macro_rules! TypestateWrite {
        (real_impl, $name:ident, $datatype:ty, <Token = $token:path>, $($rest:tt)*) => {
            impl<B: Bus + tock_registers::BusWrite<<$datatype as tock_registers::DataType>::Value>>
                TypestateWrite for $name<B>
            {
                type Token = $token;
                fn set(self, _: $token, value: <$datatype as tock_registers::DataType>::Value) {
                    // Safety: The caller assured this GenericReal points at a register on bus B with
                    // value type $datatype::Value that is safe to write. The code that constructed
                    // `self` guaranteed that they would avoid data races (precondition of Self::new).
                    unsafe { self.address.write(value) }
                }
            }
        };
        ($($unknown:tt)*) => {};
    }
}

// -------------------------------------------------------------------------------------------------
// Driver crate
// -------------------------------------------------------------------------------------------------

use core::{cell::UnsafeCell, ptr::NonNull};
use tock_registers::{mmio64_register_map, Mmio64};
use typestate::TypestateWrite;

mmio64_register_map! {
    temperature {
        // Declare that task_start and task_stop may only be written by the typestate module.
        0 => task_start: u32 { TypestateWrite<Token = wrapper::Token> },
        4 => task_stop: u32 { TypestateWrite<Token = wrapper::Token> },
    }
}

// The typestate register module, which would be generated by a procedural macro belonging to the
// typestate crate.
mod wrapper {
    use super::{temperature, TypestateWrite};

    // Token used to tie the TypestateWrite traits to this wrapper.
    pub struct Token(());

    // State types
    pub struct Off(());
    pub struct Reading(());

    pub struct Temperature<R: temperature::Interface, State> {
        registers: R,
        _state: State,
    }

    impl<R: temperature::Interface> Temperature<R, Off> {
        /// Constructs a new Temperature. This should only be called once. Unlike the DMA case,
        /// it's not *unsound* to use this peripheral incorrectly, so this doesn't need to be
        /// `unsafe`.
        pub const fn new(registers: R) -> Self {
            Self {
                registers,
                _state: Off(()),
            }
        }

        /// Start the temperature measurement. This can only be called in the Off state.
        pub fn start(self) -> Temperature<R, Reading> {
            self.registers.task_start().set(Token(()), 1);
            Temperature {
                registers: self.registers,
                _state: Reading(()),
            }
        }
    }

    impl<R: temperature::Interface> Temperature<R, Reading> {
        /// Stop the temperature measurement. This can only be called in the Reading state.
        pub fn stop(self) -> Temperature<R, Off> {
            self.registers.task_stop().set(Token(()), 1);
            Temperature {
                registers: self.registers,
                _state: Off(()),
            }
        }
    }
}

fn main() {
    // Setup: create a fake peripheral (we don't need behavior, so using Real with a local buffer
    // is fine), construct the registers, and construct the typestate wrapper.
    let peripheral = UnsafeCell::new([0u32; 2]);
    let mmio = Mmio64::new(NonNull::new(peripheral.get()).unwrap().cast());
    // Safety: Our fake peripheral is a good-enough model of the theoretical temperature
    // peripheral.
    let registers = unsafe { temperature::Real::new(mmio) };
    let temperature = wrapper::Temperature::new(registers);

    // Demonstrate use of the typestate wrapper.
    let temperature = temperature.start();
    // The following fails because the state is incorrect:
    //temperature.start();
    let _temperature = temperature.stop();
    // The following fails because the state is incorrect:
    //_temperature.stop();
}
