// Licensed under the Apache License, Version 2.0 or the MIT License.
// SPDX-License-Identifier: Apache-2.0 OR MIT
// Copyright Tock Contributors 2026.

//! Example unsafe chip crate. Contains the register map definition and DMA manager definition
//! (generated by the tock-registers and safe_dma crates, respectively).

use crate::{dma_manager, DmaEnable, UnsafeWrite};
use tock_registers::mmio64_register_map;

mmio64_register_map! {
    /// Register map for a DMA-based RNG. This RNG has a single DMA buffer. When DMA is initiated,
    /// it reads in the contents of the buffer to re-seed the RNG, then replaces the buffer with
    /// newly-generated random data.
    pub rng {
        /// Address of the DMA buffer.
        /// # Safety: As required by the safe_dma crate, this must not be modified while a DMA
        /// operation is ongoing.
        0 => address: *mut u8 { UnsafeWrite },
        /// Length of the DMA buffer.
        /// # Safety: As required by the safe_dma crate, this must not be modified while a DMA
        /// operation is ongoing.
        8 => len: usize { UnsafeWrite },
        /// DMA enable register.
        16 => enable: u8 { DmaEnable },
    }
}

dma_manager![pub RngDma, rng, address, len, enable];
